### ISSUE TITLE
add fedora-32 nodes

### ISSUE THREAD

**Issue by ssbarnea** [ansible-network/windmill-config#705]
Please make fedora-32 nodes, fedora-32 was released months ago and my impression that by the time we get it activated here we will already be outdated by fedora-33.

There are already two attempts I made to fix this but I am not sure which are the right steps (as this is also a not documented process).

https://github.com/ansible-network/windmill-config/pull/679
https://github.com/ansible-network/windmill-config/pull/680

@goneri @pabelanger ^ thanks.

Maybe not directly related to that but I would personally be happy to have a `fedora-latest` image that is updated to newer fedora whenever is made available, avoiding the need to update in all places.

There are effectively two kind of consumers: ones that want to stick to particular version and ones that only want to test with latest stable, that is why most container images also have a moving tag "latest".

**Comment by goneri** [comment]
`fedora-latest` would indeed by a nice addition. Can you add it?

**Comment by ssbarnea** [comment]
Not in this change, I will let @pabelanger comment on that first.

**Comment by goneri** [comment]
Closing, both PR have been merged. Thanks @ssbarnea.
